_extends: .github-private

repository:
  name: pass-operator
  description: A kubernetes operator that syncs and decrypts secrets from pass git repositories
  homepage: https://github.com/premiscale/pass-operator

  # A comma-separated list of topics to set on the repository
  topics: python,kubernetes,secrets,operator,pass
  private: true