fail_fast: true
repos:
  # Requires hadolint binary on local machine.
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.0-beta
    hooks:
      - id: hadolint
        args:
          - --config
          - .github/.hadolint.yaml
          - -t
          - error
          - Dockerfile

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: [--maxkb=10000, --enforce-all]
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: mixed-line-ending

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
        args:
          - -x

  - repo: https://github.com/bjd2385/dynamic-continuation-orb
    rev: v3.8.1
    hooks:
      - id: circleci-config-validate

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23
    hooks:
      - id: helmlint

  - repo: local
    hooks:
      - id: mypy
        language: script
        name: mypy
        entry: /usr/bin/env poetry run mypy
        args:
          - --non-interactive
          - --install-types
          - --config-file=pyproject.toml
        files: ^src/.*.py$
      - id: pylint
        language: script
        name: pylint
        entry: /usr/bin/env poetry run pylint
        args: []
        files: ^src/.*.py$

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.17
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check
      - id: poetry-lock

  - repo: https://github.com/python-poetry/poetry-plugin-export
    rev: 1.8.0
    hooks:
      - id: poetry-export

  - repo: https://github.com/premiscale/pre-commit-hooks
    rev: v0.0.9
    hooks:
    -   id: msg-issue-prefix

  - repo: https://github.com/bitnami/readme-generator-for-helm
    rev: 2.6.1
    hooks:
      - id: helm-readme-generator
        name: helm-readme-generator-operator
        # in order to run helm-readme-generator only once
        pass_filenames: false
        always_run: true
        # default args are [--readme=chart/README.md, --values=chart/values.yaml]
        args: [--readme=helm/operator/README.md, --values=helm/operator/values.yaml, --schema=helm/operator/values.schema.json]
      - id: helm-readme-generator
        name: helm-readme-generator-operator-e2e
        pass_filenames: false
        always_run: true
        args: [--readme=helm/operator-e2e/README.md, --values=helm/operator-e2e/values.yaml, --schema=helm/operator-e2e/values.schema.json]
      - id: helm-readme-generator
        name: helm-readme-generator-operator-crds
        pass_filenames: false
        always_run: true
        args: [--readme=helm/operator-crds/README.md, --values=helm/operator-crds/values.yaml, --schema=helm/operator-crds/values.schema.json]