fail_fast: true
repos:
  # Requires hadolint binary on local machine.
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.1-beta
    hooks:
      - id: hadolint
        args:
          - --config
          - .hadolint.yaml
          - -t
          - error
          - Dockerfile

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: [--maxkb=10000, --enforce-all]
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: mixed-line-ending

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
        args:
          - -x

  - repo: https://github.com/bjd2385/dynamic-continuation-orb
    rev: v3.8.1
    hooks:
      - id: circleci-config-validate

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23
    hooks:
      - id: helmlint

  - repo: local
    hooks:
      - id: mypy
        language: script
        name: mypy
        entry: /usr/bin/env poetry run mypy
        args:
          - --non-interactive
          - --install-types
          - --config-file=pyproject.toml
        files: src/
      - id: pylint
        language: script
        name: pylint
        entry: /usr/bin/env poetry run pylint
        args: []
        files: src/

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.15
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/python-poetry/poetry
    rev: 1.7.0
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]

  - repo: https://github.com/premiscale/pre-commit-hooks
    rev: v0.0.9
    hooks:
    -   id: msg-issue-prefix