ARG IMAGE=ubuntu
ARG TAG=22.04

FROM ${IMAGE}:${TAG}

SHELL [ "/bin/bash", "-c" ]

# https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
LABEL org.opencontainers.image.description "© PremiScale, Inc. 2024"
LABEL org.opencontainers.image.licenses "GPLv3"
LABEL org.opencontainers.image.authors "Emma Doyle <emma@premiscale.com>"
LABEL org.opencontainers.image.documentation "https://premiscale.com"

# Note: this pod is intentionally ran as root because of sshd limitations. SSHd is required for git over SSH.
# https://superuser.com/a/1548482
USER root

ARG PASS_VERSION=1.7.4-5
RUN apt update \
    && apt list -a pass \
    && apt install -y nmap net-tools openssh-server curl git pass="${PASS_VERSION}" \
    && rm -rf /var/apt/lists/* \
    && ssh-keygen -A -v \
    && mkdir -p ${HOME}/data/crd

# https://github.com/krallin/tini
ARG TINI_VERSION=v0.19.0
ARG ARCHITECTURE=arm64
RUN curl -sL https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-${ARCHITECTURE} -o /tini \
    && chmod +x /tini

RUN curl -sL https://github.com/mikefarah/yq/releases/download/v4.44.1/yq_linux_${ARCHITECTURE} -o yq \
    && install yq /usr/bin/yq \
    && rm yq

ENV PASS_DIRECTORY="" \
    PASS_GPG_KEY_ID="" \
    PASS_GPG_KEY="" \
    PASS_GPG_PASSPHRASE="" \
    PASS_GIT_BRANCH=main \
    SSH_PUBLIC_KEY="" \
    PASS_BINARY=/usr/bin/pass

COPY ./command.e2e.sh /command.e2e.sh
# Copy in the unencrypted data so we can populate the pass store when the container starts.
COPY ./data/crd/* ${HOME}/data/crd/

ENTRYPOINT [ "/tini", "--" ]
CMD [ "/command.e2e.sh" ]