version: 2.1

setup: true


orbs:
  dynamic: bjd2385/dynamic-continuation@3.6.11
  general: bjd2385/general@0.7.4


workflows:
  base-python:
    jobs:
      - dynamic/continue:
          context: circleci
          modules: |
            /scripts
            /base_python

      - general/github-release:
          context: github
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/
