version: 2.1

setup: true


orbs:
  dynamic: bjd2385/dynamic-continuation@3.8.1
  general: premiscale/general@1.0.12
  slack: circleci/slack@4.12.5


workflows:
  password-store-operator:
    jobs:
      - dynamic/continue:
          base-revision: master
          context: circleci

      - slack/on-hold:
          context: slack
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - request-approval:
          requires:
            - slack/on-hold
          type: approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/github-release:
          name: Create GitHub release from tag
          context: github
          requires:
            - request-approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/helm-release-nexus:
          name: helm build and push [helm/operator]
          context: nexus
          path: helm/operator
          requires:
            - request-approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/python-release-poetry:
          name: nexus password-store-operator upload [python]
          context: nexus
          repository: python
          requires:
            - request-approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/python-release-poetry:
          name: pypi password-store-operator upload [pypi]
          context: pypi
          repository: pypi
          requires:
            - request-approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/docker-nexus:
          name: docker [password-store-operator] [tag]
          image-name: password-store-operator
          context: nexus
          nexus-domain: $DOCKER_DOMAIN
          args: >-
            --build-arg=PYTHON_PACKAGE_VERSION=$CIRCLE_TAG
            --build-arg=PYTHON_USERNAME=$NEXUS_USERNAME
            --build-arg=PYTHON_PASSWORD=$NEXUS_PASSWORD
            --build-arg=PYTHON_REPOSITORY=python
          requires:
            - nexus password-store-operator upload [python]
            - request-approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/docker-hub:
          name: dockerhub [password-store-operator] [tag]
          image-name: password-store-operator
          context:
            - nexus
            - dockerhub
          # This installs the artifact from my private registry instead of the public one.
          args: >-
            --build-arg=PYTHON_PACKAGE_VERSION=0.0.<< pipeline.number >>
            --build-arg=PYTHON_USERNAME=$NEXUS_USERNAME
            --build-arg=PYTHON_PASSWORD=$NEXUS_PASSWORD
            --build-arg=PYTHON_REPOSITORY=python-develop
          requires:
            - nexus password-store-operator upload [python]
            - request-approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/helm-release-nexus:
          name: helm [helm/operator] [tag]
          context: nexus
          repo: $HELM_REPOSITORY_URL
          # Uses https://mikefarah.gitbook.io/yq/operators/env-variable-operators#dynamically-update-a-path-from-an-environment-variable
          image-tag-path: .deployment.image.tag
          requires:
            - dockerhub [password-store-operator] [tag]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/helm-upgrade:
          name: helm upgrade install [helm/operator] [tag]
          cluster: $CHELSEA_CLUSTER
          namespace: password-store-operator
          repo: $HELM_REPOSITORY_URL
          additional-values: |
            --set global.registry="$DOCKER_DOMAIN"
          requires:
            - helm [helm/operator] [tag]
          context:
            - kubeconfig
            - nexus
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/
