version: 2.1


orbs:
  general: premiscale/general@1.0.13


workflows:
  helm:
    jobs:
      - general/helm-lint:
          name: helm lint [<< matrix.chart-path >>]
          matrix:
            parameters:
              chart-path:
                - helm/operator
                - helm/operator-crds
            alias: helm-lint
          chart-path: << matrix.chart-path >>