version: 2.1


orbs:
  general: premiscale/general@1.0.2


executors:
  python-3-10:
    docker:
      - image: cimg/python:3.10.11


jobs:
  run-tests:
    executor: python-3-10
    resource_class: small
    steps:
      - run:
          name: Run tests
          command: |
            echo


workflows:
  helm:
    jobs:
      - run-tests