version: 2.1


orbs:
  general: premiscale/general@dev:15d6e3e08a70abbd844e3af116283638f1d54f21


workflows:
  helm:
    jobs:
      - general/helm-lint:
          name: helm lint

      - general/helm-test-kubesec:
          name: kubesec

      - general/helm-test-kubelinter:
          name: kubelinter

      - general/helm-test-deprecated:
          name: deprecated api