version: 2.1


orbs:
  general: premiscale/general@dev:8bc653b0e1690e6e2562d16ebbd3218ead2bc9d6


workflows:
  helm:
    jobs:
      - general/helm-lint:
          name: helm lint

      - general/helm-test-kubesec:
          kubeconform-schema: >-
            --schema-location https://raw.githubusercontent.com/premiscale/pass-operator/$CIRCLE_BRANCH/helm/operator-crds/templates/PassSecret.yaml
          name: kubesec

      - general/helm-test-kubelinter:
          name: kubelinter

      - general/helm-test-deprecated:
          name: deprecated api