version: 2.1


orbs:
  general: premiscale/general@1.2.0


workflows:
  helm:
    jobs:
      - general/helm-lint:
          name: helm lint

      - general/helm-test-kubesec:
          kubeconform-schema: >-
            --schema-location https://raw.githubusercontent.com/premiscale/pass-operator/$CIRCLE_BRANCH/helm/operator-crds/_json/PassSecret.json
          name: kubesec

      - general/helm-test-kubelinter:
          name: kubelinter
          # TODO: re-enable this exclude
          exclude: no-read-only-root-fs

      - general/helm-test-deprecated:
          name: deprecated api