version: 2.1


orbs:
  general: premiscale/general@dev:4de200d6e87894301096c79ce78b407d7ca4fc6a


workflows:
  helm:
    jobs:
      - general/helm-lint:
          name: helm lint

      - general/helm-test-kubesec:
          kubeconform-schema: >-
            --schema-location https://raw.githubusercontent.com/premiscale/pass-operator/$CIRCLE_BRANCH/helm/operator-crds/_json/PassSecret.json
          name: kubesec

      - general/helm-test-kubelinter:
          name: kubelinter
          # TODO: re-enable this exclude
          exclude: no-read-only-root-fs
          path: helm/operator/

      - general/helm-test-deprecated:
          name: deprecated api