version: 2.1


executors:
  python-3-10:
    docker:
      - image: cimg/python:3.12.4


orbs:
  general: premiscale/general@1.2.8


jobs:
  python-tests-unit:
    executor: python-3-10
    resource_class: small
    steps:
      - checkout
      - general/python-install-poetry
      - run:
          name: Poetry install
          command: |+
            poetry install
      - run:
          name: Python unit tests
          command: |+
            poetry run pytest --junitxml=junit_test_results.xml src/test/unit
      - store_test_results:
          path: ./junit_test_results.xml

  # python-tests-e2e:



workflows: {}
  # tests:
  #   jobs:
  #     - python-tests-unit:
  #         name: python unit tests