global:
  image:
    registry: docker.io


deployment:
  # A list of pull secret names.
  pullSecrets: []

  image:
    name: pass-operator-e2e
    tag: ignore
    pullPolicy: Always

  resources:
    requests:
      cpu: 0.25
      memory: 500Mi
    limits:
      cpu: 0.25
      memory: 500Mi

  livenessProbe:
    enabled: false
    port: 22
    config: {}

  podSecurityContext: {}

  containerSecurityContext: {}


# The following job is used both to initialize the git repository and to populate the e2e pass store with secrets / data.
job:
  activeDeadlineSeconds: 600
  pullSecrets: []

  image:
    name: pass-operator-e2
    tag: ignore
    pullPolicy: Always

  resources:
    requests:
      cpu: 0.25
      memory: 500Mi
    limits:
      cpu: 0.25
      memory: 500Mi

  ssh:
    createSecret: false

    name: private-ssh-key

    # raw string of the secret key b64enc'd.
    value: ""

  gpg:
    createSecret: false

    name: private-gpg-key

    key_id: ""
    value: ""
    passphrase: ""

  git:
    branch: main


initializeRepoJob:
  command: [ /entrypoint.e2e.init.sh ]


operator:
  pass:
    binary: /usr/bin/pass
    storeSubPath: ""

  ssh:
    # If create is false, value is not used; users may bring their own.
    createSecret: false

    # Name of the secret. If createSecret is false, this is used to reference an existing, user-provided secret.
    name: public-ssh-key

    # raw string of the secret key b64enc'd.
    value: ""

  gpg:
    createSecret: false

    # Name of the secret. If createSecret is false, this is used to reference an existing, user-provided secret.
    name: public-gpg-key

    key_id: ""
    value: ""
    passphrase: ""

  git:
    branch: main


service:
  create: true
  type: ClusterIP
  ports:
    - name: ssh
      port: 22
      targetPort: 22