{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ ((.Values.rbac.clusterrolebinding).name) | default .Chart.Name }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  {{- with ((.Values.rbac.rolebinding).labels) }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with ((.Values.rbac.rolebinding).annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Values.global.namespace | default .Release.Namespace }}
    name: {{ .Values.serviceAccount.name | default .Chart.Name }}
roleRef:
  kind: ClusterRole
  name: {{ ((.Values.rbac.clusterrole).name) | default .Chart.Name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}