{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ ((.Values.rbac.clusterrole).name) | default .Chart.Name }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  {{- with ((.Values.rbac.clusterrole).labels) }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with ((.Values.rbac.clusterrole).annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - "*"

  # https://github.com/nolar/kopf/issues/901#issuecomment-1063911897
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - list
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - "*"
    verbs:
      - list
      - watch
{{- end }}