apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ default .Values.deployment.name .Chart.Name }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  {{- with .Values.deployment.labels }}
  labels:
    {{- range $k, $v := . }}
    {{ $k }}: {{ tpl $v $ }}
    {{- end }}
  {{- end }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- range $k, $v := . }}
    {{ $k }}: {{ tpl $v $ }}
    {{- end }}
  {{- end }}
spec:
  ## DeploymentSpec v1 core
  {{- with .Values.deployment.minReadySeconds }}
  minReadySeconds: {{ . }}
  {{- end }}
  {{- with .Values.deployment.progressDeadlineSeconds }}
  progressDeadlineSeconds: {{ . }}
  {{- end }}
  replicas: {{ .Values.deployment.replicas | default 1 }}
  {{- with .Values.deployment.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if ne (int64 .Values.deployment.revisionHistoryLimit) 10 }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit | default 10 }}
  {{- end }}
  # Select which pods (by label) this Deployment spec is targeting.
  selector:
    matchLabels: {{ include "password-store-operator.selectorLabels" . | nindent 6 }}
  template:
    ## PodTemplateSpec v1 core
    metadata:
      {{- with .Values.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels: {{ include "password-store-operator.selectorLabels" . | nindent 8 }}
    spec:
      ## PodSpec v1core
      {{- with .Values.deployment.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ . }}
      {{- end }}
      {{- with .Values.deployment.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.hostIPC }}
      hostIPC: {{ . }}
      {{- end }}
      {{- with .Values.deployment.hostNetwork }}
      hostNetwork: {{ . }}
      {{- end }}
      {{- if gt (len ((((.Values).deployment).pullSecrets) | default "")) 0 }}
      imagePullSecrets:
        {{- range $secret := .Values.deployment.pullSecrets }}
        - name: {{ $secret }}
        {{- end }}
      {{- end }}
      {{- if ne (default .Values.deployment.serviceAccountName "default") "default" }}
      serviceAccountName: {{ .Values.deployment.serviceAccountName }}
      {{- end }}
      {{- with .Values.deployment.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.nodeName }}
      nodeName: {{ . | quote }}
      {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        ## Container v1 core (array)
        - name: {{ tpl (default .Values.deployment.name .Chart.Name) $ }}
          args: >-
            --log-stdout
            --interval "$PASSWORD_STORE_OPERATOR_INTERVAL"
            --log-level "$PASSWORD_STORE_LOG_LEVEL"
            --pass-binary "$PASS_BINARY"
            --pass-dir "$PASS_DIRECTORY"
            --gpg-key-id "$GPG_KEY_ID"
            --git-ssh-url "$GIT_SSH_URL"
            --git-branch "$GIT_BRANCH"
          {{- with .Values.deployment.extraArgs }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.stdin }}
          stdin: {{ . }}
          {{- end }}
          {{- with .Values.deployment.stdinOnce }}
          stdinOnce: {{ . }}
          {{- end }}
          {{- if (((.Values).deployment).terminationMessagePath) }}
          terminationMessagePath: {{ .Values.deployment.terminationMessagePath | quote }}
          {{- end }}
          env:
            - name: PASSWORD_STORE_OPERATOR_LOG_LEVEL
              value: {{ .Values.deployment.pass_store.log_level }}
            - name: PASSWORD_STORE_OPERATOR_INTERVAL
              value: {{ .Values.deployment.pass_store.interval }}
            - name: PASS_BINARY
              value: {{ .Values.deployment.pass_store.pass_binary }}
            - name: PASS_DIRECTORY
              value: {{ .Values.deployment.pass_store.pass_directory }}
            - name: GIT_SSH_URL
              value: {{ .Values.deployment.pass_store.git.url }}
            - name: GIT_BRANCH
              value: {{ .Values.deployment.pass_store.git.branch }}
            - name: GPG_KEY_ID
              value: {{ .Values.deployment.pass_store.gpg_key_id }}
            - name: SSH_PRIVATE_KEY
              {{- with .Values.deployment.pass_store.ssh_key }}
              {{- if .secret.create }}
              valueFrom:
                secretKeyRef:
                  key: {{ .secret.key }}
                  name: {{ .secret.name }}
              {{- else }}
              value: {{ .secret.value }}
              {{- end }}
              {{- end }}
          {{- with .Values.deployment.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.tty }}
          tty: {{ . }}
          {{- end }}
          {{- with .Values.deployment.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if (((.Values.global).image).registry) }}
          image: {{ .Values.global.image.registry }}/{{ .Values.deployment.image.name }}:{{ .Values.deployment.image.tag }}
          {{- else }}
          image: {{ .Values.deployment.image.registry }}/{{ .Values.deployment.image.name }}:{{ .Values.deployment.image.tag }}
          {{- end }}
          imagePullPolicy: {{ default .Values.deployment.image.pullPolicy "Always" }}
          {{- if or ((.Values.deployment.lifecycle).preStop) ((.Values.deployment.lifecycle).postStart) }}
          lifecycle:
            {{- with .Values.deployment.lifecycle.preStop }}
            preStop:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.deployment.lifecycle.postStart }}
            postStart:
              {{- toYaml . | nindent 14 }}
            {{- end }}
          {{- end }}
          {{- with .Values.deployment.startupProbe }}
            {{- if .enabled }}
          startupProbe:
            httpGet:
              path: {{ .path }}
              port: {{ .port }}
            {{- toYaml .config | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .Values.deployment.livenessProbe }}
            {{- if .enabled }}
          livenessProbe:
            httpGet:
              path: {{ .path }}
              port: {{ .port }}
            {{- toYaml .config | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .Values.deployment.readinessProbe }}
            {{- if .enabled }}
          readinessProbe:
            httpGet:
              path: {{ .path }}
              port: {{ .port }}
            {{- toYaml .config | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .Values.deployment.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.volumeDevices }}
          volumeDevices:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}