apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ default .Values.deployment.name .Chart.Name }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  {{- with .Values.deployment.labels }}
  labels:
    {{- range $k, $v := . }}
    {{ $k }}: {{ $v }}
    {{- end }}
  {{- end }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- range $k, $v := . }}
    {{ $k }}: {{ $v }}
    {{- end }}
  {{- end }}
spec:
  ## DeploymentSpec v1 core
  replicas: {{ .Values.deployment.replicas | default 1 }}
  revisionHistoryLimit: 1
  # Select which pods (by label) this Deployment spec is targeting.
  selector:
    matchLabels: {{ include "pass-operator.selectorLabels" . | nindent 6 }}
  template:
    ## PodTemplateSpec v1 core
    metadata:
      {{- with .Values.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels: {{ include "pass-operator.selectorLabels" . | nindent 8 }}
    spec:
      ## PodSpec v1core
      {{- if gt (len ((((.Values).deployment).pullSecrets) | default "")) 0 }}
      imagePullSecrets:
        {{- range $secret := .Values.deployment.pullSecrets }}
        - name: {{ $secret }}
        {{- end }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name | default .Chart.Name }}
      {{- end }}
      {{- with .Values.deployment.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- with .Values.operator.git.volume }}
        - name: pass
          emptyDir:
            medium: Memory
            sizeLimit: {{ .sizeLimit }}
        {{- end }}
        {{- with .Values.operator.gpg.volume }}
        - name: gpg
          emptyDir:
            medium: Memory
            sizeLimit: {{ .sizeLimit }}
        {{- end }}
        {{- with .Values.operator.ssh.volume }}
        - name: ssh
          emptyDir:
            medium: Memory
            sizeLimit: {{ .sizeLimit }}
        {{- end }}
      containers:
        ## Container v1 core (array)
        - name: {{ default .Values.deployment.name .Chart.Name }}
          args: [
            --log-stdout,
            --log-level, {{ .Values.operator.log.level }}
          ]
          {{- with .Values.deployment.livenessProbe }}
            {{- if .enabled }}
          ports:
            - containerPort: {{ .port }}
              name: healthcheck
              protocol: TCP
            {{- end }}
          {{- end }}
          volumeMounts:
            - name: pass
              mountPath: /opt/pass-operator/.password-store/{{ .Values.operator.pass.subdirectory }}
              readOnly: false
            - name: gpg
              mountPath: /opt/pass-operator/.gnupg/
              readOnly: false
            - name: ssh
              mountPath: /opt/pass-operator/.ssh/
              readOnly: false
          env:
            # Operator
            - name: OPERATOR_INTERVAL
              value: {{ .Values.operator.interval | quote }}
            - name: OPERATOR_INITIAL_DELAY
              value: {{ .Values.operator.initial_delay | quote }}
            - name: OPERATOR_PRIORITY
              value: {{ .Values.operator.priority | quote }}
            - name: OPERATOR_NAMESPACE
              value: {{ .Values.global.namespace | default .Release.Namespace }}
            - name: OPERATOR_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: OPERATOR_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            # Pass
            - name: PASS_BINARY
              value: {{ .Values.operator.pass.binary }}
            - name: PASS_DIRECTORY
              value: {{ .Values.operator.pass.subdirectory }}
            - name: PASS_GPG_KEY
              {{- with .Values.operator.gpg }}
                {{- if .createSecret }}
              valueFrom:
                secretKeyRef:
                  key: ssh-privatekey
                  name: {{ .name }}
                {{- else }}
              value: {{ .value }}
                {{- end }}
              {{- end }}
            - name: PASS_GPG_PASSPHRASE
              {{- with .Values.operator.gpg }}
                {{- if .createSecret }}
              valueFrom:
                secretKeyRef:
                  key: passphrase
                  name: {{ .name }}
                {{- else }}
              value: {{ .passphrase }}
                {{- end }}
              {{- end }}
            - name: PASS_GPG_KEY_ID
              value: {{ .Values.operator.gpg.key_id }}
            - name: PASS_GIT_URL
              value: {{ .Values.operator.git.url }}
            - name: PASS_GIT_BRANCH
              value: {{ .Values.operator.git.branch }}
            - name: PASS_SSH_PRIVATE_KEY
              {{- with .Values.operator.ssh }}
                {{- if .createSecret }}
              valueFrom:
                secretKeyRef:
                  key: ssh-privatekey
                  name: {{ .name }}
                {{- else }}
              value: {{ .value }}
                {{- end }}
              {{- end }}
          {{- with .Values.deployment.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if (((.Values.global).image).registry) }}
          image: {{ .Values.global.image.registry }}/{{ .Values.deployment.image.name }}:{{ .Values.deployment.image.tag }}
          {{- else }}
          image: {{ .Values.deployment.image.registry }}/{{ .Values.deployment.image.name }}:{{ .Values.deployment.image.tag }}
          {{- end }}
          imagePullPolicy: {{ default .Values.deployment.image.pullPolicy "Always" }}
          {{- with .Values.deployment.startupProbe }}
            {{- if .enabled }}
          startupProbe:
            httpGet:
              path: {{ .path }}
              port: {{ .port }}
            {{- with .config }}
            {{- toYaml .| nindent 12 }}
            {{- end }}
            {{- end }}
          {{- end }}
          {{- with .Values.deployment.livenessProbe }}
            {{- if .enabled }}
          livenessProbe:
            httpGet:
              path: {{ .path }}
              port: {{ .port }}
            {{- with .config }}
            {{- toYaml .| nindent 12 }}
            {{- end }}
            {{- end }}
          {{- end }}
          {{- with .Values.deployment.readinessProbe }}
            {{- if .enabled }}
          readinessProbe:
            httpGet:
              path: {{ .path }}
              port: {{ .port }}
            {{- with .config }}
            {{- toYaml .| nindent 12 }}
            {{- end }}
            {{- end }}
          {{- end }}
          {{- with .Values.deployment.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}