{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default .Chart.Name }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  {{- with .Values.serviceAccount.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- if gt (len ((((.Values).deployment).pullSecrets) | default "")) 0 }}
imagePullSecrets:
  {{- range $secret := .Values.deployment.pullSecrets }}
  - name: {{ $secret }}
  {{- end }}
{{- end }}
{{- if gt (len ((((.Values).serviceAccount).secrets) | default "")) 0 }}
secrets:
  {{- range $secret := .Values.serviceAccount.secrets }}
  - apiVersion: {{ $secret.apiVersion }}
    namespace: {{ .Values.global.namespace | default .Release.Namespace }}
    name: {{ $secret.name }}
  {{- end }}
{{- end }}
{{- end }}