{{- with .Values.operator.ssh }}
  {{- if .createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.global.namespace | default $.Release.Namespace }}
  {{- with .labels }}
  labels:
    {{- range $k, $v := . }}
    {{ $k }}: {{ tpl $v $ }}
    {{- end }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    {{- range $k, $v := . }}
    {{ $k }}: {{ tpl $v $ }}
    {{- end }}
  {{- end }}
immutable: true
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: {{ .value }}
  {{- end }}
{{- end }}