global:
  image:
    registry: docker.io


deployment:
  image:
    name: pass-operator
    tag: latest
    pullPolicy: Always

  resources:
    requests:
      cpu: 0.25
      memory: 500Mi
    limits:
      cpu: 0.25
      memory: 500Mi


operator:
  interval: 60
  initial_delay: 3
  priority: 100

  pass:
    binary: /usr/bin/pass
    subdirectory: repo

  log:
    level: info
    location: /opt/pass-operator/runtime.log

  ssh:
    # If create is false, value is not used; users may bring their own.
    createSecret: false

    # Specs of the secret if createSecret is true; otherwise, these fields are used to reference an existing secret.
    name: private-ssh-key

    # raw string of the secret key b64enc'd.
    value: ""

  gpg:
    createSecret: false

    # Specs of the secret if createSecret is true; otherwise, these fields are used to reference an existing secret.
    name: private-gpg-key

    key_id: ""
    value: ""

  git:
    branch: main
    url: ""


service:
  create: true
  type: ClusterIP
  ports:
    - appProtocol: http
      name: http
      port: 443
      targetPort: 443


serviceAccount:
  create: true