global:
  image:
    registry: docker.io


deployment:
  image:
    name: pass-operator
    tag: ignore
    pullPolicy: Always

  resources:
    requests:
      cpu: 0.25
      memory: 500Mi
    limits:
      cpu: 0.25
      memory: 500Mi

  livenessProbe:
    enabled: true
    port: 8080
    path: /healthz
    config: {}

  podSecurityContext:
    runAsNonRoot: true
    readOnlyRootFilesystem: true


operator:
  interval: 60
  initial_delay: 3
  priority: 100

  pass:
    binary: /usr/bin/pass
    subdirectory: repo

  log:
    level: info
    location: /opt/pass-operator/runtime.log

  ssh:
    # If create is false, value is not used; users may bring their own.
    createSecret: false

    # Name of the secret. If createSecret is false, this is used to reference an existing, user-provided secret.
    name: private-ssh-key

    # raw string of the secret key b64enc'd.
    value: ""

  gpg:
    createSecret: false

    # Name of the secret. If createSecret is false, this is used to reference an existing, user-provided secret.
    name: private-gpg-key

    key_id: ""
    value: ""
    passphrase: ""

    volume:
      sizeLimit: 100Ki

  git:
    branch: main
    url: ""

    # Memory-based filesystem to store git repository.
    volume:
      sizeLimit: 20Mi


service:
  create: false
  # type: ClusterIP
  # ports:
  #   - appProtocol: http
  #     name: http
  #     port: 443
  #     targetPort: 443


serviceAccount:
  create: true

# Namespace-local PassSecrets require RBAC setup for operator access through the ServiceAccount.
role: {}
rolebinding: {}

# Cluster-wide Secrets require RBAC setup for operator access through the ServiceAccount.
clusterrole: {}
clusterrolebinding: {}