global:
  image:
    registry: docker.io


deployment:
  image:
    name: password-store-operator
    tag: latest
    pullPolicy: Always

  resources:
    requests:
      cpu: 0.25
      memory: 500Mi
    limits:
      cpu: 0.25
      memory: 500Mi

  env:
    - name: PASSWORD_STORE_OPERATOR_LOG_LEVEL
      value: info
    - name: PASSWORD_STORE_OPERATOR_INTERVAL
      value: 60


service:
  create: true
  type: ClusterIP
  ports:
    - appProtocol: http
      name: http
      port: 443
      targetPort: 443


serviceAccount:
  create: true