global:
  image:
    registry: docker.io


deployment:
  image:
    name: password-store-operator
    tag: latest
    pullPolicy: Always


service:
  create: true
  type: ClusterIP
  ports:
    - appProtocol: http
      name: http
      port: 443
      targetPort: 443


serviceAccount:
  create: true