apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.job.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.job.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  activeDeadlineSeconds: {{ .Values.job.activeDeadlineSeconds }}
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.job.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.job.enabled }}
          serviceAccountName: {{ .Chart.Name }}
          {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              command: {{ .Values.job.command }}
              {{- if .Values.global.image.registry }}
              image: "{{ .Values.global.image.registry }}/{{ .Values.job.image.name }}:{{ .Values.job.image.tag }}"
              {{- else }}
              image: "{{ .Values.job.image.name }}:{{ .Values.job.image.tag }}"
              {{- end }}
              imagePullPolicy: Always
              {{- with .Values.job.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              env:
                # Pass
                - name: PASS_BINARY
                  value: {{ .Values.operator.pass.binary }}
                - name: PASS_DIRECTORY
                  value: {{ .Values.operator.pass.storeSubPath }}
                - name: PASS_GPG_KEY
                  {{- with .Values.operator.gpg }}
                    {{- if .createSecret }}
                  valueFrom:
                    secretKeyRef:
                      key: ssh-privatekey
                      name: {{ .name }}
                    {{- else }}
                  value: {{ .value }}
                    {{- end }}
                  {{- end }}
                - name: PASS_GPG_PASSPHRASE
                  {{- with .Values.operator.gpg }}
                    {{- if .createSecret }}
                  valueFrom:
                    secretKeyRef:
                      key: passphrase
                      name: {{ .name }}
                    {{- else }}
                  value: {{ .passphrase }}
                    {{- end }}
                  {{- end }}
                - name: PASS_GPG_KEY_ID
                  {{- with .Values.operator.gpg }}
                    {{- if .createSecret }}
                  valueFrom:
                    secretKeyRef:
                      key: id
                      name: {{ .name }}
                    {{- else }}
                  value: {{ .key_id }}
                    {{- end }}
                  {{- end }}
                - name: PASS_GIT_BRANCH
                  value: {{ .Values.operator.git.branch }}
                - name: SSH_PRIVATE_KEY
                  valueFrom:
                    secretKeyRef:
                      key: ssh-privatekey
                      name: private-ssh-key
          {{- if gt (len .Values.job.pullSecrets) 0 }}
            {{- range .Values.job.image.pullSecrets }}
          imagePullSecrets:
            - name: {{ . }}
            {{- end }}
          {{- end }}
          restartPolicy: Never